### PR TITLE
add a dump of build info

### LINKED ISSUE #185: generate a text report on what hpc-stack installs, and where it comes from
We need a list of what hpc-stack installs, and where it is getting each package from.

Instead of generating a one-time list, I think hpc-stack should be able to output a simple list of what it would install. Possible?

Also we have been requested to add a package description and a notation whether the package is in the operational stack or not.

So, we want the following:
* package name
* version
* brief package description
* source
* operational or not

### PR DESCRIPTION
**Pull request by aerorahul**
Partially closes #185 
Adds a report of what is being built and what version and from where was the package obtained from.
The PR generates a list like this during build:
```
==========================
build_info()
build: esmf | version: 8_1_0_beta_snapshot_21
build: eckit | version: release-stable
build: ecbuild | version: release-stable
build: pio | version: 2.5.2
build: ncio | version: develop
build: json | version: 3.9.1
build: crtm | version: v2.3.0
build: atlas | version: release-stable
build: landsfcutil | version: v2.4.1
build: hdf5 | version: 1.10.6
build: w3emc | version: v2.7.3
build: grib_util | version: v1.2.2
build: cdo | version: 1.9.8
build: pybind11 | version: 2.5.0
build: wrf_io | version: v1.1.1-cmake-v5
build: nemsio | version: v2.5.2
build: bacio | version: v2.4.1
build: fckit | version: release-stable
build: nemsiogfs | version: v2.5.3
build: nccmp | version: 1.8.7.0
build: json_schema_validator | version: 2.1.0
build: netcdf | version:
build: jasper | version: 2.0.25
build: zlib | version: 1.2.11
build: ip2 | version: v1.1.2
build: eigen | version: 3.3.7
build: bufr | version: bufr_v11.4.0
build: upp | version: upp_v10.0.0
build: w3nco | version: v2.4.1
build: gfsio | version: v1.4.1
build: gsl_lite | version: 0.37.0
build: jpeg | version: 9.1.0
build: mpi | version: 3.3.1
build: boost | version: 1.68.0
build: szip | version: 2.1.1
build: wgrib2 | version: v2.0.8-cmake-v6
build: sigio | version: v2.3.2
build: prod_util | version: v1.2.2
build: g2c | version: v1.6.2
build: sp | version: v2.3.3
build: g2tmpl | version: v1.9.1
build: g2 | version: v3.4.1
build: ip | version: v3.3.3
build: png | version: 1.6.35
build: sfcio | version: v1.4.1
==========================
```

At the end of the build (or while in progress), the user can inspect a file in `${HPC_STACK_ROOT}/hpc-stack-contents.log`
The contents of the file will show:
```
name_of_the_package version_of_the_package URL_from_where_the_package_was_obtained
```
e.g.
```
bufr bufr_v11.4.0 https://github.com/noaa-emc/nceplibs-bufr
```

### CODE REVIEW

**Review by kgerheiser — APPROVED** [review]

**Comment by edwardhartnett** [comment]
We need the source in this output as well. In fact, that is one of the most important things. Apparently not just packages are approved, but also sources. We have to get approved packages from approved sources, so we need to see all the packages and all the sources, so the list can be checked...

**Comment by aerorahul** [comment]
Checked each time? Why?

**Comment by edwardhartnett** [comment]
The list can be checked and then new packages will be checked as they are added, but we should still be able to print out a list of this information whenever someone asks for it.

It is a reasonable question to ask: what does hpc-stack install, exactly, and where does it come from? Let's make it easy to answer that question...

**Comment by aerorahul** [comment]
Fair enough. I can add an echo statement during the build.

**Comment by aerorahul** [comment]
> The list can be checked and then new packages will be checked as they are added, but we should still be able to print out a list of this information whenever someone asks for it.
> 
> It is a reasonable question to ask: what does hpc-stack install, exactly, and where does it come from? Let's make it easy to answer that question...

fixed in b80db9f

**Review by kgerheiser — APPROVED** [review]

**Pull request merged**
