### PR TITLE
Fix CDO build by separating LDFLAGS and LIBS env variables

### PR DESCRIPTION
**Pull request by kgerheiser**
This fixes a build problem with CDO on WCOSS Dell (and probably other machines), and potentially #201.

I think LDFLAGS is used in this manner in other libraries, and is potentially related to https://github.com/NOAA-EMC/hpc-stack/issues/149 because `-lm` would then come at the end of the link line and use the Intel math library. 

Which throws this warning
`icc: warning #10315: specifying -lm before files may supersede the Intel(R) math library and affect performance`

Though, for now I'm just leaving it at CDO.

### CODE REVIEW

**Review by aerorahul — COMMENTED** [review]
This is great @kgerheiser 
I think we may need to do this elsewhere where we do this black magic;  e.g. nccmp, nco, etc.

**Comment by climbfuji** [comment]
> This is great @kgerheiser
> I think we may need to do this elsewhere where we do this black magic; e.g. nccmp, nco, etc.

Testing this now on Cheyenne ...

**Comment by climbfuji** [comment]
@kgerheiser @aerorahul I have a small PR for Kyle's branch: https://github.com/kgerheiser/hpc-stack/pull/1/files

This removed stack_ncar (now identical to stack_noaa, because Kyle's bugfix works) and updates upp/nceppost in all other stack files. Please take a look both, and if you agreee merge it into Kyle's branch. Thanks!

**Review by climbfuji — APPROVED** [review]
Works on Cheyenne!

**Comment by kgerheiser** [comment]
NCO and NCCMP use a CMake build which I don't think is affected.

**Comment by aerorahul** [comment]
> NCO and NCCMP use a CMake build which I don't think is affected.

True, but.
in `build_nccmp.sh`
```
 cmake .. \
        -DBUILD_TESTS=OFF \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_EXE_LINKER_FLAGS="$LDFLAGS" \
        -DCMAKE_INSTALL_PREFIX=$prefix \
        -DCMAKE_VERBOSE_MAKEFILE=ON \
        -DNETCDF_INC_DIR=$NETCDF_ROOT/include \
        -DNETCDF_LIB_PATH=$NETCDF_ROOT/lib/libnetcdf.a \
        -DWITH_NETCDF=${netcdf_src:-}
```

`LDFLAGS` is obtained as before.

**Review by aerorahul — APPROVED** [review]
looks good.

**Pull request merged**
