### PR TITLE
Documentation updates for MacOS and Linux

### PR DESCRIPTION
**Pull request by natalie-perlin**
## DESCRIPTION OF CHANGES: 
1. Documentation updates for building the hpc-stack on MacOS and Linux, from the latest NOAA-EMC:develop branch. Updated README file with the instructions to build the documentation.
2. Updated stack/*yaml files. Set building a compiler to "NO" as a default. Removed a duplicate that followed earlier naming convention (*mac_*gnu*), and left the version with *macos* naming convention.

Files changed:
**./docs/mac-install.rst
./docs/hpc-install.rst
./docs/hpc-prereqs.rst
README**

### Type of change
- [x] Documentation updates
- [x] configuration file update

## CONTRIBUTORS: 
README instructions: credit to @gspetro-NOAA

### CODE REVIEW

**Review by AlexanderRichert-NOAA — COMMENTED** [review]
What are the changes in the two yaml files for? I don't see those mentioned in the description of changes.

**Comment by natalie-perlin** [comment]
@AlexanderRichert-NOAA  - 
 Updated a description of the changes. As to *yaml files the changes were the following:
a) Set building a compiler to "NO" as a default. b) Removed a duplicate that followed earlier naming convention (*mac_gnu), and left the version with *macos* naming convention.

**Comment by AlexanderRichert-NOAA** [comment]
@natalie-perlin Got it, thanks for your patience on this one. Is the idea of setting the compiler build to NO by default to save time, or is there a deeper reason?

**Comment by natalie-perlin** [comment]
@AlexanderRichert-NOAA   - yes, there is a need to turn off the compiler build, as per our documentation, it is installed using Homebrew on MacOS systems, and using "sudo apt install " on Linux.

**Review by AlexanderRichert-NOAA — APPROVED** [review]
Sorry for the delay. Looks good.

**Pull request merged**
