### PR TITLE
Add boostrap option for CMake

### LINKED ISSUE #220: Update CMake to 3.20.1
Building the weather model with external FMS requires CMake 3.19+ which will be installed with hpc-stack.

### PR DESCRIPTION
**Pull request by kgerheiser**
Platforms with CMake already installed can disable bootstrap (boostrap: NO) and use the exisiting CMake to build the new CMake and save compile time.

Fixes #220

### CODE REVIEW

**Review by aerorahul — APPROVED** [review]
looks good.

**Comment by kgerheiser** [comment]
CMake doesn't build on macOS using GCC because of some system header `Authorization.h`. Need to use Clang. I'm going to disable building it for macOS so that the CI can pass.

**Comment by edwardhartnett** [comment]
Why are we building CMake instead of just requiring it?

**Comment by kgerheiser** [comment]
We don't normally build it because it's available on our systems already. However, that is not always the case on all systems, or the version is too old. So, we have the option to build it. 

For the weather model to use the external build of FMS in hpc-stack it needs a newer version of CMake, and the quickest way to deploy that across our systems while we wait for system admins to install it is to use hpc-stack because that's already how we manage other libraries.

**Pull request merged**
