### PR TITLE
Set FMS AVX2 flags for Cheyenne, patch FMS for GNU 9/10 on Cheyenne

### PR DESCRIPTION
**Pull request by climbfuji**
Here is a suggestion to apply patches to packages that will work not just for FMS.

Also set the AVX2 flags for compiling FMS. Not sure if these should be the default in `libs/build_fms.sh` or not, therefore just adding to the Cheyenne configs for now.

Suggestions welcome. Whatever solution we adopt should make it into v1.2.0 in my opinion.

### CODE REVIEW

**Comment by aerorahul** [comment]
elegant.  
Don't forget to add the patch to the repo.

**Comment by climbfuji** [comment]
> elegant.
> Don't forget to add the patch to the repo.

Thanks! Turns out I had to remove `*.patch` from `.gitignore`, too.

**Comment by climbfuji** [comment]
Same here, can I get a review or even better an approval? Thanks!

**Review by aerorahul — APPROVED** [review]
Looks good.

**Pull request merged**
