### PR TITLE
add g2c

### LINKED ISSUE #56: Installation Request: g2c/1.6.0 on WCOSS
I am working with NCO to get MET (https://github.com/dtcenter/MET) version 9.1.0 into operations. It was discovered when compiling MET with g2c/1.5.0 on both the Dell and Cray lead to a problem to arise. When MET is compiled with g2c/1.6.0, the problem goes away. I am requesting for g2c/1.6.0 to be installed on all WCOSS machines.

### PR DESCRIPTION
**Pull request by Hang-Lei-NOAA**
g2c_v1.6.2 is added into hpc-stack.

### CODE REVIEW

**Review by aerorahul — CHANGES_REQUESTED** [review]
@Hang-Lei-NOAA 
This looks good.
Missing is a modulefile, please add one.

**Comment by Hang-Lei-NOAA** [comment]
yes, forgot to git add that file

**Review by aerorahul — APPROVED** [review]
Looks good.
Will merge after CI finishes.

BTW the issue #56 requests v1.6.0 of g2c.  This PR is installing v1.6.2.  Please check with @malloryprow if there is an issue with using a later version for their purpose.

**Comment by Hang-Lei-NOAA** [comment]
Okay, the code of g2_1.6.2 is not changed, it should be fine for ME . 1.6.0 does not work with the new jasper version in hpc-stack. Kyle and I updated it to get it working with new jasper versions last month. Documentation by Ed is also added.

**Comment by edwardhartnett** [comment]
Does this mean you have done a new release of g2c?

**Comment by Hang-Lei-NOAA** [comment]
Yes, we can either build from develop or tag.
But tag is required for hpc-stack installation.

**Comment by edwardhartnett** [comment]
The VERSION file was not updated in NCEPLIBS-g2c. I have entered an issue.

**Pull request merged**
