### PR TITLE
Build python virtual environments.

### PR DESCRIPTION
**Pull request by aerorahul**
This PR:

- adds ability to build python virtual environments and load them as modules.  This is a desired functionality for users of applications that require different combinations of python packages.
- This functionality is currently being exercised in JEDI related projects such as EWOK, JEDI-GDAS HofX applications.
- This functionality can be leveraged for other applications requiring python virtual environments e.g. JEDI-SOCA, MetPlus, etc.

To load a python virtual env. is the same as loading any other library or utility.  Loading the module will place the user in the python virtual env. (akin to `source venv/bin/activate`).  Unloading `deactivate`'s the virtual environment.

Also in this PR, 
- the yaml files have been moved to `stack/` from `config/`
- virtual environment `requirements.txt` files will be placed under `pyvenv/`
- Updates to `README.md` on how to add a virtual environment and correct paths for JEDI dependencies

### CODE REVIEW

**Comment by aerorahul** [comment]
@kgerheiser 
Can I please get a review on this?

**Comment by kgerheiser** [comment]
Are the JEDI repositories private? I tried building r2d2, but it asks for a Github password.

**Comment by aerorahul** [comment]
Yes. They are private at the moment and hence the build is turned OFF.

**Review by kgerheiser — APPROVED** [review]

**Comment by aerorahul** [comment]
thanks @kgerheiser

**Comment by edwardhartnett** [comment]
We are going to move from hpc-stack to spack for distributing our libraries. How will this capability be transitioned?

**Comment by aerorahul** [comment]
That is for you to figure out.

**Comment by climbfuji** [comment]
> We are going to move from hpc-stack to spack for distributing our libraries. How will this capability be transitioned?

I am surprised to hear that the decision to move to spack was already made, but maybe I misunderstood the discussion yesterday. I think it is a good approach, but it needs more testing (we have roadmap for it) and it's not set in stone yet. Whatever we agree on, there'll be a lot of things that need to be transitioned (by someone).

**Pull request merged**
