### PR TITLE
Feature/mac gnu

### PR DESCRIPTION
**Pull request by natalie-perlin**
Updated compiler options, configuration files for building the hpc-stack on Mac OSX machines: m1/arm64 and Intel/x86_64

### CODE REVIEW

**Comment by kgerheiser** [comment]
I am confused about these PRs. Why do you merge `NOAA-EPIC:feature/mac_gnu` into `NOAA-EMC:feature/mac_gnu`. These feature branches should exist on the EPIC fork and when they are ready to be merged should be merged into develop. They are not long-term branches that we keep around on the main repository.

**Comment by natalie-perlin** [comment]
@kgerheiser - That's a good point, will keep this in mind. So the PR needs to be `NOAA-EPIC:feature/mac_gnu` --> `NOAA-EMC:develop
`

**Comment by kgerheiser** [comment]
PRs should go into develop as a general rule. If you maintain a feature branch on your fork that's fine, but when you make a PR it should go into develop. That is the default branch that everyone uses. Otherwise your changes get merged into a difference feature branch in the hpc-stack repo that nobody uses.

**Comment by natalie-perlin** [comment]
Will it make sense to  take out the `NOAA-EMC:feature/cheyenne` branch, too?. Even though it has some specifics of getting the right modules loaded for building the hpc-stack in the environment with a large number of modules and versions.

**Pull request merged**
