### PR TITLE
feature/hpc-stack-nco: merge Cheyenne updates from develop

### PR DESCRIPTION
**Pull request by climbfuji**
This PR merges updates from Cheyenne that were made for the develop branch (https://github.com/NOAA-EMC/hpc-stack/pull/38, commits cherry-picked and conflicts resolved) into the feature/hpc-stack-nco.

This works on Cheyenne with both Intel and GNU.

### CODE REVIEW

**Comment by edwardhartnett** [comment]
Please enter an issue describing these changes.

Moving forward, all PRs must be accompanied by an issue on this and all other NCEPLIBS repos. If there is not an issue for your PR, make one.

Thanks!

**Comment by climbfuji** [comment]
> Please enter an issue describing these changes.
> 
> Moving forward, all PRs must be accompanied by an issue on this and all other NCEPLIBS repos. If there is not an issue for your PR, make one.
> 
> Thanks!

Done. I can't link the issue since I don't have sufficient (at least triage) rights in hpc-stack.

**Comment by edwardhartnett** [comment]
In your description if you say Fixes #62 or Part of #62, then the issue will be linked to the PR by github.

**Comment by Hang-Lei-NOAA** [comment]
I think it is no technique concerns to push into the branch.

**Pull request merged**
