### PR TITLE
Correct the location of the g2 library paths

### PR DESCRIPTION
**Pull request by DavidHuber-NOAA**
Corrected the location of the `$G2_LIB4` and `$G2_LIBd` environmental variables (for libg2_4.a and libg2_d.a, respectively) in the g2.lua module file template to be g2/lib64 instead of g2/lib.

### CODE REVIEW

**Comment by kgerheiser** [comment]
This is not correct because it can be either `lib` or `lib64` depending on the system. If you change it to `${CMAKE_INSTALL_LIBDIR}` then I can approve this PR.

**Comment by kgerheiser** [comment]
See here for an example: https://github.com/NOAA-EMC/hpc-stack/blob/develop/modulefiles/compiler/compilerName/compilerVersion/wgrib2/wgrib2.lua

**Comment by DavidHuber-NOAA** [comment]
I gave this a quick test build on S4 and it sets the variables as expected.  Thanks!

**Review by kgerheiser — APPROVED** [review]

**Comment by edwardhartnett** [comment]
Is there an issue for this? If not, please add one.

**Comment by kgerheiser** [comment]
https://github.com/NOAA-EMC/hpc-stack/issues/265

**Pull request merged**
