### PR TITLE
Feature/mac gnu

### PR DESCRIPTION
**Pull request by natalie-perlin**
Removed redundant flags/options for building mapl, from stack/mac*yaml

### CODE REVIEW

**Comment by kgerheiser** [comment]
@natalie-perlin your PRs are confusing me. You merged `NOAA-EPIC:feature/mac_gnu` into `NOAA-EMC:feature/mac_gnu` after you closed your previous PR (which just need to be re-approved). Is this what you meant to  do?

**Comment by natalie-perlin** [comment]
I think it's all good now with the feature/mac_gnu. It has been merged into the develop on NOAA-EMC, 
`NOAA-EMC:feature/mac_gnu` into `NOAA-EMC:develop`, if I understand correctly

**Comment by kgerheiser** [comment]
You don't want to merge this into develop?

**Comment by natalie-perlin** [comment]
So the PR #420 was only to NOAA-EMC:feature/mac_gnu, not into the develop?.. Then yes, #413 needs to be reopened and re-approved!

**Pull request merged**
