### PR TITLE
add UPP to hpc-stack

### LINKED ISSUE #31: Update the nceppost with request by using the 10.0.0 version
Wen has added the nceppost with UPP version of 10.0.0. She request the installation test through hpc-stack.
We will first try it from the EMC_POST/develop branch, on each machine.
If it is okay, she needs to create a release to formally included in the hpc-stack.

A branch has been created to this issue
feature/postupdate

### PR DESCRIPTION
**Pull request by aerorahul**
This PR:
- adds UPP v10 to the hpc-stack
- retains nceppost until it is ready to be removed and replaced by UPP for post library in UFS
- fixes #31 

Change-Id: I09a155ef0e026d8fac682390f05e9c2dd9c7c2d4

### CODE REVIEW

**Comment by aerorahul** [comment]
Looks like there is a bug in upp_v10.0.0

**Comment by kgerheiser** [comment]
I don't know why it does that here specifically. I was able to build the tag fine, and it builds on the Action I setup for their repository.

**Comment by aerorahul** [comment]
Yeah. I haven't got to why yet.  Help appreciated.  Mind boggling indeed.

**Comment by climbfuji** [comment]
What is the problem?

**Comment by kgerheiser** [comment]
https://github.com/NOAA-EMC/hpc-stack/pull/63/checks#step:4:23250

**Comment by edwardhartnett** [comment]
Do we need this PR to work for the 1.1.0 release? Seems like that is implied by #71

**Comment by aerorahul** [comment]
Yes.

**Comment by kgerheiser** [comment]
Maybe related, maybe not, but is there a problem with building two versions of UPP, v10.0.0 and the dcea26 version? When installed in a flat structure, as we do on the Github Runner, modules like `vrbls3d` will overwrite one another? Or it picks up the one module first and it doesn't contain some of the variables?

**Comment by aerorahul** [comment]
Good point @kgerheiser
I'll disable nceppost in the runner and keep UPP and then re-run the ci. 
Let's see.

**Comment by climbfuji** [comment]
> Good point @kgerheiser
> I'll disable nceppost in the runner and keep UPP and then re-run the ci.
> Let's see.

Great finding, @kgerheiser. We don't need both at the same time, as far as I can see.

**Comment by aerorahul** [comment]
reopened this PR.
The CI was successful with nceppost turned off.  @kgerheiser was correct to identify the issue in the comments above.  Thanks @kgerheiser

**Comment by aerorahul** [comment]
woops. missing something here.

**Pull request closed without merging**
