### PR TITLE
Updated documentation for MacOS build of hpc-stack

### PR DESCRIPTION
**Pull request by natalie-perlin**
Updated documentation  in ./docs/source/:
 - corrected directions for the MacOS HPC-stack build 
 - removed a library from the list of hpc-stack components that is no longer being built within the stack
 - made some smaller updates and clarifications

### CODE REVIEW

**Review by kgerheiser — APPROVED** [review]

**Comment by kgerheiser** [comment]
@natalie-perlin there are some conflicts.

**Comment by natalie-perlin** [comment]
> @natalie-perlin there are some conflicts.

@kgerheiser - thank you, resolved!

**Comment by grantfirl** [comment]
@natalie-perlin Is there a list somewhere of successful installations for M1 Macs? I recently got a new M1 MBP and am trying to install hpc-stack with GNU 11.3.0. I've followed the mac installation instructions, but I'm running into a compilation error with HDF5 that kills the installation. Is it as simple as using the EXACT compiler versions listed in the docs?

**Comment by kgerheiser** [comment]
Can you show the error (or open a new issue)? I don't have an M1 Mac myself, but other people have tested various builds with succcess.

**Comment by natalie-perlin** [comment]
@grantfirl - GNU 11.3.0 (Homebrew GNU 11.3.0/ GNU 11.2.0) used to work for Mac M1. It would be helpful to know the error you are getting. The easiest way would be to take a look at the  `./hpc-stack/log/hdf5.log ` file generated during the installation, as a link to a cloud location, or attached.

**Comment by grantfirl** [comment]
Thanks @kgerheiser and @natalie-perlin . I've started a new issue: https://github.com/NOAA-EMC/hpc-stack/issues/463 with the attached hdf5.log from my attempted installation.

**Pull request merged**
