### PR TITLE
feature/hpc-stack-nco: add support for gaea with lua modules

### PR DESCRIPTION
**Pull request by climbfuji**
This PR is for feature/hpc-stack-nco. It enables building hpc-stack on gaea for the following hash of the ufs-weather-model:
```
commit b771e5be7e35eaea5ee7f762d644afccab019ed3 (HEAD -> develop, origin/develop, origin/HEAD)
Author: Jun Wang <37633869+junwang-noaa@users.noreply.github.com>
Date:   Tue Nov 17 16:52:48 2020 -0500

    Bring GFS.v16 features back to develop branch (#274)
```
It is my understanding that the feature/hpc-stack-nco branch will in one or the other way be sent back to develop (but presumably no straight merge?), in which case the changes here will create conflicts with @aerorahul's changes for gaea for the develop branch. I will take care of resolving these if needed.

As a general note, I feel that we are over-specifying the ESMF build. For instance, it is not necessary to set `ESMF_OS`, since this is detected in almost all cases when the ESMF_COMPILER and ESMF_COMM variables are set correctly. For gaea, I had to comment out setting `ESMF_OS`, which was hardcoded to `Linux`. The correct settings for gaea are `ESMF_COMM=mpi` and `ESMF_OS=Unicos` (which is detected correctly).

### CODE REVIEW

**Comment by climbfuji** [comment]
If the relevant changes of the feature/hpc-stack-nco branch are sent back to develop soon, then this PR does not need to be merged. Will keep it open for now, just in case it is needed.

**Comment by kgerheiser** [comment]
I'm having a hard time telling what needs to be merged in from that other branch and what doesn't.

**Comment by edwardhartnett** [comment]
@climbfuji  please stop using NOAA-EMC:feature/hpc-stack-nco. See #84.

Moving forward, all changes will be made to develop branch.

**Comment by climbfuji** [comment]
> I'm having a hard time telling what needs to be merged in from that other branch and what doesn't.

Welcome to the club. I would entirely ignore this PR, because "develop" will have gaea updates merged soon (#70). This PR here was in case feature/hpc-stack-nco is around for longer and I need to reinstall new versions of the feature branch. We should never have done that anyway, installing a version based on a feature branch to be used by authoritative repositories.

**Comment by climbfuji** [comment]
> @climbfuji please stop using NOAA-EMC:feature/hpc-stack-nco. See #84.
> 
> Moving forward, all changes will be made to develop branch.

These changes are not required to go to develop, develop already has a PR #70. This PR here is a result of the unfortunate decision to install a feature branch on all platforms and use it in the authoritative repositories. I am going to close it to avoid further confusion.

**Pull request closed without merging**
