### PR TITLE
Mapl v2.22.0

### PR DESCRIPTION
**Pull request by kgerheiser**
@jkbk2004 does this match the proposed installs for #471

### CODE REVIEW

**Comment by jkbk2004** [comment]
@kgerheiser mapl-2.22.0 needs -DUSE_EXTDATA2G=OFF to build_mapl.sh

**Comment by kgerheiser** [comment]
Is that a runtime or build issue? I was able to build MAPL fine without touching that setting.

**Review by Hang-Lei-NOAA — APPROVED** [review]

**Comment by jkbk2004** [comment]
> Is that a runtime or build issue? I was able to build MAPL fine without touching that setting.

Its build option regarding aerosol emission file choice.

**Comment by kgerheiser** [comment]
Added that option into the MAPL build

**Review by jkbk2004 — APPROVED** [review]
We can close this PR with @ChunxiZhang-NOAA test confirmation.

**Comment by ChunxiZhang-NOAA** [comment]
@jkbk2004 The tests on Hera were successful.  Please close this PR.

**Comment by jkbk2004** [comment]
@kgerheiser please, go ahead to install new mapl and gftl_shared on gaea/jet/orion.

**Comment by jkbk2004** [comment]
@kgerheiser can we make sure the new mapl and gftl_shared installed on orion/jet/gaea? We will start merging in Chunxi.PR with the new mapl and gftl_shared versions.

**Comment by kgerheiser** [comment]
Yes, doing it now

**Comment by jkbk2004** [comment]
Thanks!

**Comment by kgerheiser** [comment]
I am unable to login to `Orion-devel-1` to update the build there at the moment. Might be related to the maintenance that Orion just got back from.

**Comment by jkbk2004** [comment]
@kgerheiser I think Orion-devel-1 is available now. Can you install this morning?

**Comment by kgerheiser** [comment]
Done

**Comment by jkbk2004** [comment]
@kgerheiser @ChunxiZhang-NOAA I don't see new mapl/gftl_sahred
orion

**Comment by jkbk2004** [comment]
@kgerheiser @ChunxiZhang-NOAA can you install to hpc/1.1.0 there? That's the version we currently use.

**Comment by ChunxiZhang-NOAA** [comment]
@kgerheiser Please install to hpc/1.1.0.

**Comment by kgerheiser** [comment]
Maybe you need a `module --ignore_cache avail`

**Comment by jkbk2004** [comment]
Sorry and Sure! module --ignore_cache avail works. It's installed there! Thanks @kgerheiser

**Pull request merged**
