### PR TITLE
Changes for compiling community GSI/EnKF

### PR DESCRIPTION
**Pull request by guoqing-noaa**
1. Add the lib `gsiwrfio` which is required to compile regional applications of community GSI/EnKF. It needs more codes beyond current `wrf_io` in the NCEPLIBS and it looks like it is not a trivial task to combine "gsiwrfio" and "wrf_io"

2. Add `config_comgsi.sh` and `stack_comgsi.yaml` to build only libraries required by community GSI/EnKF.

### CODE REVIEW

**Comment by aerorahul** [comment]
What is the difference between comgsi's version of the wrf_io library and NCEPLIBS-wrf_io? 
And, why is it built as part of NCEPLIB's if it is not part of NCEPLIBS?

**Comment by guoqing-noaa** [comment]
There are two big differences:
1. gsi/enkf wrfio needs the following files which do not exist in NCEPLIBS-wrf_io
io_int_stubs.f90
model_data_order.inc
module_driver_constants.F90
module_machine.F90
pack_utils.c
streams.h

2. For "warning" messages, 
NCEPLIBS-wrf_io uses "wrf_message(...)"  while GSI/EnKF wrfio uses "wrf_debug(...)"
In order to combine them into one, we need to change either UPP or GSI/EnKF source code,  Or we need to add compiling flags to compile UPP or GSI respectively. 

Latest NOAA GSI/EnKF was updated to use hpc-stack, it is a natural choice for community GSI/EnKF users to adopt the same structure. It is better to include gsiwrfio in the NCEPLIBS so community users does not need to get all required libraries in two separate steps. I hope it can be incorporated in an official way.  Also in the next two years before the regional FV3LAM goes into operation, if we want to recompile GSI for RAP/HRRR at wcoss, we need this gsiwrfio.  Currently EMC runs HRRR-based RTMA3D in the development stage at wcoss, if they want to compile GSI, they need this gsiwrfio also. So I think we cannot say this is not a part of NCEPLIBS.

**Comment by edwardhartnett** [comment]
All libraries which become part of NCEPLIBS must include doxygen documentation and unit tests.

What is the state of gsiwrfio with regard to documentation and testing? What is the plan to bring documentation and testing up to standard?

**Comment by guoqing-noaa** [comment]
@edwardhartnett  Thanks for the comments. I don't think I have time to maintain/update this lib according to NCEPLIBS rules (such as adding doxygen documentation and unit tests). I hope it can be merged with current NCEPLIBS-wrf_io in some way but I am okay with any official decisions on this.  

Feel free to close this PR if no more efforts will be made on this.

**Comment by aerorahul** [comment]
@guoqing-noaa 
Your issue and need is legitimate.  The GSI regional configuration needs this library.  This library used to reside in the GSI repository under `libsrc/` and was not coordinated with the NCEPLibs team until recently.  
This issue has been raised and @kgerheiser has a PR in NCEPLIBS-wrf_io.  I don't think it is far-off from your version.  I encourage working with @kgerheiser and getting your repository synchronised with NCEPLIBS-wrf_io or atleast giving it a look to justify why the separate libraries need to exist.

hpc-stack has no issues installing your package (you provide the build instructions and support for this library).
If it fails, you will be pinged or the package will be disabled from the stack until the issue is resolved.

**Comment by guoqing-noaa** [comment]
@aerorahul  Thanks for the information. I did not realize there was already a PR in NCEPLIBS-wrf_io to address this issue (we waited this for a very long time...). I will try to work with @kgerheiser to get things sorted out. Thanks again!

**Comment by guoqing-noaa** [comment]
Close this one as all changes in gsiwrfio have been merged into latest wrf_io (v1.2.0). Thanks all for comments and helps.

**Pull request closed without merging**
