### PR TITLE
Add stack yaml file for ufs weather ci test

### PR DESCRIPTION
**Pull request by MinsukJi-NOAA**
Do not build JEDI related libraries to save space when running CI test for ufs-weather-model.

### CODE REVIEW

**Comment by aerorahul** [comment]
@MinsukJi-NOAA 
You can just delete the sections that you don't want to build e.g. everything after `boost`, just remove them from the yaml.

Also, do you really want to build shared libs for netcdf, hdf5, etc?

**Comment by MinsukJi-NOAA** [comment]
> @MinsukJi-NOAA
> You can just delete the sections that you don't want to build e.g. everything after `boost`, just remove them from the yaml.
> 
> Also, do you really want to build shared libs for netcdf, hdf5, etc?

I will delete them.

I didn't have problem building and running the ufs-weahter-model.  What are the benefits you see for using static library?

**Comment by aerorahul** [comment]
There is no problem at all.  Just consistent with how the stack is built on NOAA HPC's.

**Review by aerorahul — APPROVED** [review]
looks good.

**Pull request merged**
